from auto4dstem.viz.viz import Strain_Compare, basis2probe, real_strain_viz, strain_tensor_for_real, visual_rotation, visual_strain_magnitude
import h5py
import numpy as np


from dataclasses import dataclass, field
from m3util import Printer, filter_kwargs, remove_all_ticks
from m3util.viz.colorbars import add_colorbar
from m3util.viz.layout import subfigures
from m3util.viz.text import labelfigs


@dataclass
class VisualizeExperimental:
    rotation: any
    scale_shear: any
    file_py4DSTEM: any = None
    angle_shift: float = 0
    shift_ref: float = 0
    im_size: any = (256, 256)
    bkg_position: int = 0
    classification: any = None
    title_name: str = "WS2WSe2"
    folder_name: str =  "./data/figures"
    cmap_strain: str = "RdBu_r"
    cmap_rotation: str = "twilight"
    inverse_rotation: bool = False
    add_label: bool = True
    label_style: str = "wb"
    rotation_range: list[float] = field(default_factory=list)
    ref_rotation_range: list[float] = field(default_factory=list)
    """ class for visualizing and comparing 

    Args:
        rotation (numpy.array): rotation value generated by neural network
        scale_shear (numpy.array): scale and shear value generated by neural network
        file_py4DSTEM (str): hdf5 file of affine parameter generated by py4DSTEM
        angle_shift (float): determine the additional degree added to the rotation for visualization, neural network
        shift_ref (float): determine the additional degree added to the rotation for visualization, py4DSTEM
        im_size (tuple): size of the strain map
        bkg_position (int): index of background position in classification
        classification (numpy.array, optional): classification generated by neural network. Default to None.
        title_name (str): title of the figure
        folder_name (str): folder to save the figure
        cmap_strain (str): color map of plt.imshow
        cmap_rotation (str): color map of plt.imshow
        supplementary_angle (bool): determine if the show the supplenmentary angle when comparing with each other
        add_lable (bool): determine if add label to figure
        label_style (str): determine label style. Defaults to 'wb'
        rotation_range (list): range of rotation value for visualization  
        ref_rotation_range (list): range of rotation value for visualization 
    """

    def __post_init__(self):
        # create folder to save results
#        make_folder(self.folder_name)
        # create background index and sample index according to classification matrix
        if self.classification is not None:
            # generate index of sample position
            sample_position = int(1 - self.bkg_position)
            # create background index and sample index
            self.bkg_index = np.where(self.classification[:, self.bkg_position] == 1)[0]
            self.sample_index = np.where(self.classification[:, sample_position] == 1)[
                0
            ]

        else:
            # if no classification, set background index and sample index to be None
            self.bkg_index = None
            self.sample_index = None

        # load the h5 file of py4DSTEM results
        if self.file_py4DSTEM is not None:
            f = h5py.File(self.file_py4DSTEM)
            self.strain_map = f["strain_map_root"]["strain_map"]["data"][:]
            # load strain parameters of py4DSTEM from strain map file
            self.exx_correlation = self.strain_map[0, :, :].reshape(-1)
            self.eyy_correlation = self.strain_map[1, :, :].reshape(-1)
            self.exy_correlation = self.strain_map[2, :, :].reshape(-1)

            # set value in background position to be -1
            if self.classification is not None:
                self.exx_correlation[self.bkg_index] = -1
                self.eyy_correlation[self.bkg_index] = -1
                self.exy_correlation[self.bkg_index] = -1

            # reshape affine parameter into image size
            self.exx_correlation = self.exx_correlation.reshape(self.im_size)
            self.eyy_correlation = self.eyy_correlation.reshape(self.im_size)
            self.exy_correlation = self.exy_correlation.reshape(self.im_size)

            # compare performance of rotation value and visualize it
            self.theta_correlation, self.theta_ae = self.compare_rotation(
                title_name=self.title_name,
                cmap=self.cmap_rotation,
                shift_ref=self.shift_ref,
                img_size=self.im_size,
                clim=self.rotation_range,
                ref_clim=self.ref_rotation_range,
                inverse_rotation=self.inverse_rotation,
                add_label=self.add_label,
                label_style=self.label_style,
            )

        else:
            # visualize the performance of rotation value
            self.theta_ae = visual_rotation(
                self.rotation,
                classification=self.classification,
                bkg_index=self.bkg_index,
                sample_index=self.sample_index,
                title_name=self.title_name,
                folder_name=self.folder_name,
                cmap=self.cmap_rotation,
                angle_shift=self.angle_shift,
                img_size=self.im_size,
                clim=self.rotation_range,
                add_label=self.add_label,
                label_style=self.label_style,
            )

        # generate affine matrices by affine parameters
        self.M_init = basis2probe(self.rotation, self.scale_shear).reshape(-1, 2, 2)
        # get strain parameters of neural network from strain_tensor function
        self.exx_ae, self.eyy_ae, self.exy_ae = strain_tensor_for_real(
            self.M_init, self.im_size, sample_index=self.sample_index
        )

    def reset_angle(
        self,
        angle_shift,
        rotation_range=[0.01, 60],
        ref_rotation_range=[0.01, 60],
        shift_ref=0,
        inverse_rotation=False,
        label_style=None,
    ):
        """function to compare performance of rotation value and visualize it

        Args:
            angle_shift (float): additional degree value added to the rotation of neural network
            rotation_range (list, optional): range of rotation value for visualization. Defaults to [0.01,60].
            shift_ref (float, optional): additional degree value added to the rotation of py4DSTEM. Defaults to 0.
            label_style (str, optional): determine label style. Defaults to None
        """

        self.angle_shift = angle_shift
        self.rotation_range = rotation_range
        self.ref_rotation_range = ref_rotation_range
        self.shift_ref = shift_ref
        self.inverse_rotation = inverse_rotation
        # initial label style
        if label_style is not None:
            self.label_style = label_style
        # compare performance of rotation value and visualize it
        if self.file_py4DSTEM is not None:
            self.theta_correlation, self.theta_ae = self.compare_rotation(
                title_name=self.title_name,
                cmap=self.cmap_rotation,
                shift_ref=self.shift_ref,
                img_size=self.im_size,
                clim=self.rotation_range,
                ref_clim=self.ref_rotation_range,
                inverse_rotation=self.inverse_rotation,
                add_label=self.add_label,
                label_style=self.label_style,
            )
        else:
            # visualize the performance of rotation value
            self.theta_ae = visual_rotation(
                self.rotation,
                classification=self.classification,
                bkg_index=self.bkg_index,
                sample_index=self.sample_index,
                title_name=self.title_name,
                folder_name=self.folder_name,
                cmap=self.cmap_rotation,
                angle_shift=self.angle_shift,
                img_size=self.im_size,
                clim=self.rotation_range,
                add_label=self.add_label,
                label_style=self.label_style,
            )

    def reset_baseline(self):
        """
        function to reload the h5 file of py4DSTEM results
        """

        # load the h5 file of py4DSTEM results
        f = h5py.File(self.file_py4DSTEM)
        self.strain_map = f["strain_map_root"]["strain_map"]["data"][:]
        self.exx_correlation = self.strain_map[0, :, :].reshape(-1)
        self.eyy_correlation = self.strain_map[1, :, :].reshape(-1)
        self.exy_correlation = self.strain_map[2, :, :].reshape(-1)

        # set value in background position to be -1
        if self.classification is not None:
            self.exx_correlation[self.bkg_index] = -1
            self.eyy_correlation[self.bkg_index] = -1
            self.exy_correlation[self.bkg_index] = -1
        # reshape affine parameter into image size
        self.exx_correlation = self.exx_correlation.reshape(self.im_size)
        self.eyy_correlation = self.eyy_correlation.reshape(self.im_size)
        self.exy_correlation = self.exy_correlation.reshape(self.im_size)

    def reset_polar_matrix(self):
        """
        function to reload affine matrices with affine parameters
        """
        self.M_init = basis2probe(self.rotation, self.scale_shear).reshape(-1, 2, 2)
        self.exx_ae, self.eyy_ae, self.exy_ae = strain_tensor_for_real(
            self.M_init, self.im_size, sample_index=self.sample_index
        )

    def visual_strain(
        self,
        strain_range_xx_ae=[-0.03, 0.015],
        strain_range_yy_ae=[-0.035, 0.005],
        strain_range_xy_ae=[-0.012, 0.02],
        strain_range_xx_cross=[0.05, 0.15],
        strain_range_yy_cross=[0.05, 0.15],
        strain_range_xy_cross=[-0.05, 0.05],
        label_style=None,
    ):
        """function to visualize strain performance between results of py4DSTEM and neural network

        Args:
            strain_range_xx_ae (list, optional): visualization range of strain x of neural network. Defaults to [-0.03,0.015].
            strain_range_yy_ae (list, optional): visualization range of strain y of neural network. Defaults to [-0.035,0.005].
            strain_range_xy_ae (list, optional): visualization range of shear of neural network. Defaults to [-0.012,0.02].
            strain_range_xx_cross (list, optional): visualization range of strain x of py4DSTEM. Defaults to [0.05,0.15].
            strain_range_yy_cross (list, optional): visualization range of strain y of py4DSTEM. Defaults to [0.05,0.15].
            strain_range_xy_cross (list, optional): visualization range of shear of py4DSTEM. Defaults to [-0.05,0.05].
            title_name (str, optional): title of the figure. Defaults to 'WS2WSe2'.
            label_style (str, optional): determine label style. Defaults to None
        """

        self.strain_range_xx_ae = strain_range_xx_ae
        self.strain_range_yy_ae = strain_range_yy_ae
        self.strain_range_xy_ae = strain_range_xy_ae
        self.strain_range_xx_cross = strain_range_xx_cross
        self.strain_range_yy_cross = strain_range_yy_cross
        self.strain_range_xy_cross = strain_range_xy_cross
        # initial label style
        if label_style is not None:
            self.label_style = label_style

        # generate list of color range by initialized parameters
        self.strain_list = [
            self.exx_correlation,
            self.eyy_correlation,
            self.exy_correlation,
            self.theta_correlation,
            self.exx_ae,
            self.eyy_ae,
            self.exy_ae,
            self.theta_ae,
        ]
        # save results in h5 file
        hf = h5py.File(
            f"{self.folder_name}/{self.title_name}_real_strain_list_with_py4d.h5", "w"
        )
        hf.create_dataset(f"py4d", data=self.strain_list[0:4])
        hf.create_dataset(f"auto4d", data=self.strain_list[4:])
        hf.close()

        # visualize strain comparison between results of py4DSTEM and neural network
        Strain_Compare(
            self.strain_list,
            ae_xx_diff_range=self.strain_range_xx_ae,
            ae_yy_diff_range=self.strain_range_yy_ae,
            ae_xy_diff_range=self.strain_range_xy_ae,
            cross_xx_diff_range=self.strain_range_xx_cross,
            cross_yy_diff_range=self.strain_range_yy_cross,
            cross_xy_diff_range=self.strain_range_xy_cross,
            rotation_range=self.rotation_range,
            ref_rotation_range=self.ref_rotation_range,
            title_name=self.title_name,
            folder_name=self.folder_name,
            cmap_strain=self.cmap_strain,
            cmap_rotation=self.cmap_rotation,
            add_label=self.add_label,
            label_style=self.label_style,
        )

    def visual_real_strain(
        self,
        strain_range_xx_ae=[-0.03, 0.015],
        strain_range_yy_ae=[-0.035, 0.005],
        strain_range_xy_ae=[-0.012, 0.02],
        label_style=None,
    ):
        """function to visualize strain performance of neural network results

        Args:
            strain_range_xx_ae (list, optional): visualization range of strain x of neural network. Defaults to [-0.03,0.015].
            strain_range_yy_ae (list, optional): visualization range of strain y of neural network. Defaults to [-0.035,0.005].
            strain_range_xy_ae (list, optional): visualization range of shear of neural network. Defaults to [-0.012,0.02].
            label_style (str, optional): determine label style. Defaults to None
        """
        self.strain_range_xx_ae = strain_range_xx_ae
        self.strain_range_yy_ae = strain_range_yy_ae
        self.strain_range_xy_ae = strain_range_xy_ae
        # initial label style
        if label_style is not None:
            self.label_style = label_style
        # generate list of color range by initialized parameters
        self.strain_list = [self.exx_ae, self.eyy_ae, self.exy_ae, self.theta_ae]
        # save results in h5 file
        hf = h5py.File(f"{self.folder_name}/{self.title_name}_real_strain_list.h5", "w")
        hf.create_dataset(f"auto4d", data=self.strain_list)
        hf.close()
        # visualize strain performance of neural network results
        real_strain_viz(
            self.strain_list,
            title_name=self.title_name,
            folder_name=self.folder_name,
            cmap_strain=self.cmap_strain,
            cmap_rotation=self.cmap_rotation,
            ae_xx_diff_range=self.strain_range_xx_ae,
            ae_yy_diff_range=self.strain_range_yy_ae,
            ae_xy_diff_range=self.strain_range_xy_ae,
            rotation_range=self.rotation_range,
            add_label=self.add_label,
            label_style=self.label_style,
        )

    def visual_magnitude_of_strain(
        self,
        strain_range=[-2.5, 2.5],
        ref_range=[-3, 3],
        only_real=False,
        label_style=None,
    ):
        """function to visualize strain magnitude

        Args:
            strain_range (list, optional): visualization range of neural network strain magnitude. Defaults to [-2.5,2.5].
            ref_range (list, optional): visualization range of py4DSTEM strain magnitude. Defaults to [-3,3].
            only_real (bool, optional): determine if only neural network results to be visualized. Defaults to False.
            label_style (str, optional): determine label style. Defaults to None
        """

        self.strain_range = strain_range
        self.ref_range = ref_range
        self.only_real = only_real
        # initial label style
        if label_style is not None:
            self.label_style = label_style
        # set strain x and strain y of py4DSTEM if file_py4DSTEM is True
        if self.file_py4DSTEM is not None:
            ref_xx = self.exx_correlation
            ref_yy = self.eyy_correlation
        else:
            ref_xx = None
            ref_yy = None

        # visualize strain magnitude
        visual_strain_magnitude(
            self.exx_ae,
            self.eyy_ae,
            title_name=self.title_name,
            folder_name=self.folder_name,
            cmap=self.cmap_strain,
            sample_index=self.sample_index,
            ref_xx=ref_xx,
            ref_yy=ref_yy,
            strain_range=self.strain_range,
            ref_range=self.ref_range,
            img_size=self.im_size,
            only_real=self.only_real,
            add_label=self.add_label,
            label_style=self.label_style,
        )

    def compare_rotation(
        self,
        title_name="WS2WSe2",
        cmap="RdBu_r",
        shift_ref=0,
        img_size=(256, 256),
        clim=[0, 60],
        inverse_rotation=False,
        save_figure=True,
        add_label=True,
        label_style="wb",
        inset_fraction = (0.1,0.07),
        **kwargs,
    ):
        """function to compare rotation map between results of neural network and py4DSTEM

        Args:
            strain_map (numpy.array): strain map results generated by py4DSTEM
            rotation_ (numpy.array): rotation matrix generated by neural network
            classification (numpy.array, optional): If exists, classification map generated by neural network. Defaults to None.
            bkg_index (numpy.array, optional): if classification is not None, index of background map. Defaults to None.
            sample_index (numpy.array, optional): if classification is not None, index of sample map. Defaults to None.
            title_name (str, optional): name of the figure. Defaults to 'WS2WSe2'.
            folder_name (str): folder to save the figure.
            cmap (str): color map of plt.imshow.
            angle_shift (float, optional): angle degree shift on rotation map neural network. Defaults to 0.
            shift_ref (float, optional): angle degree shift on rotation map py4DSTEM. Defaults to 0.
            img_size (tuple, optional): size of the rotation map. Defaults to (256,256).
            clim (list, optional): visualization range of rotation value. Defaults to [0,60].
            save_figure (bool, optional): determine save or not.
            add_label (bool, optional): determine if add label to the figure.
            label_style (str, optional): determine if add label to figure. Defaults to 'wb'.

        Returns:
            numpy.array: adjusted of rotation value for py4DSTEM and neural network
        """
        kwargs.setdefault("inset_fraction", inset_fraction)
        kwargs.setdefault("style", label_style)
        ref_clim = kwargs.get("ref_clim", clim)
        rotational_symmetry_degree = kwargs.get("rotational_symmetry_degree", 60)

        # set name of the figure
        name_ = self.get_title(title_name)

        # switch format to degree for each rotation value, mod by 60 to make it distributed in (0, 60)
        theta_correlation = self.extract_shifted_rotation_degrees(
            shift_ref, rotational_symmetry_degree
        )
        if self.classification is not None:
            theta_correlation[self.bkg_index] = 0

        temp_ae = self.inverse_rotational_transformation(
            self.angle_shift, inverse_rotation, rotational_symmetry_degree
        )
        theta_ae = self.zero_background(
            self.bkg_index, self.sample_index, img_size, temp_ae
        )

        # reshape the rotation map into 2D image size
        theta_correlation = theta_correlation.reshape(img_size)
        theta_ae = theta_ae.reshape(img_size)

        # visualize the rotation map and histogram
        fig, ax = subfigures(2, 2, gaps=(0.4, 0.1))
        ax = np.array(ax).reshape(2, 2)

        remove_all_ticks([ax[0, 0], ax[0, 1]])

        im1 = ax[0, 0].imshow(
            theta_correlation,
            cmap=cmap,
            vmin=ref_clim[0],
            vmax=ref_clim[1],
        )
        add_colorbar(im1, ax[0, 0])

        ax[1, 0].hist(theta_correlation.reshape(-1), 200, range=ref_clim)
        im2 = ax[0, 1].imshow(
            theta_ae,
            cmap=cmap,
            vmin=clim[0],
            vmax=clim[1],
        )
        add_colorbar(im2, ax[0, 1])

        ax[1, 1].hist(theta_ae.reshape(-1), 200, range=clim)

        ax[1, 0].xaxis.set_label_text("Rotation (degree)")
        ax[1, 1].xaxis.set_label_text("Rotation (degree)")
        if add_label:
            labelfigs(
                ax[0, 0], string_add="Py4DSTEM", loc="ct", inset_fraction=(inset_fraction[0],0), style= label_style
            )
            labelfigs(
                ax[0, 1], string_add="Auto4DSTEM", loc="ct", inset_fraction=(inset_fraction[0],0), style= label_style
            )
        if save_figure:
            print(self.folder_name)
            filtered_kwargs = filter_kwargs(Printer, kwargs)
            printer = Printer(basepath=self.folder_name, **filtered_kwargs)
            printer.savefig(
                fig, f"/Rotation_comparison_on_{name_}", label_figs=ax.ravel(), **kwargs
            )

        return theta_correlation, theta_ae
    def zero_background(self, background_index, sample_index, img_size, temp_ae):
        if background_index is not None:
            # make rotation map region where belongs to background become 0, keep sample region value.
            theta_ae = np.zeros([img_size[0] * img_size[1]])
            theta_ae[sample_index] = temp_ae
            return theta_ae
        else:
            return temp_ae

    def inverse_rotational_transformation(
        self, angle_shift, inverse_rotation, rotational_symmetry_degree
    ):
        rotation_ = rotational_symmetry_degree if inverse_rotation else 0
        inverse_rotation_ = -1 if inverse_rotation else 1

        temp_ae = np.mod(
            angle_shift
            + rotation_
            + inverse_rotation_
            * np.rad2deg(
                np.arctan2(
                    self.rotation[:, 1].reshape(-1), self.rotation[:, 0].reshape(-1)
                )
            ),
            rotational_symmetry_degree,
        )

        return temp_ae

    def extract_shifted_rotation_degrees(self, shift_ref, rotational_symmetry_degree):
        return np.mod(
            shift_ref + np.rad2deg(self.strain_map[3, :, :]), rotational_symmetry_degree
        ).reshape(-1)
        
    @staticmethod
    def get_title(title_name):
        if isinstance(title_name, str):
            name_ = title_name
        else:
            name_ = format(title_name, ".2f") + " Background Noise"
        return name_