from auto4dstem.viz.viz import (
    MAE_diff_with_Label,
    Strain_Compare,
    basis2probe,
    cal_diff,
    hist_plotter,
    strain_tensor,
)


import h5py
import matplotlib.pyplot as plt
import numpy as np
from m3util import Printer, filter_kwargs, remove_all_ticks
from m3util.viz.colorbars import add_colorbar
from m3util.viz.layout import subfigures
from m3util.viz.text import labelfigs
from skimage import morphology
from skimage.morphology import binary_erosion
from dataclasses import dataclass, field


@dataclass
class VisualizeSimulation:
    rotation: any
    scale_shear: any
    file_py4DSTEM: str
    label_rotation_path: str = "rotation_label_2.npy"
    label_xx_path: str = "Label_strain_xx.npy"
    label_yy_path: str = "Label_strain_yy.npy"
    label_xy_path: str = "Label_shear_xy.npy"
    noise_intensity: float = 0.0
    folder_name: str = "./data/figures"
    cmap_strain: str = "RdBu_r"
    cmap_rotation: str = "twilight"
    cmap_mae: str = "viridis"
    angle_shift: float = 0
    im_size: any = (256, 256)
    ref_region: any = (30, 60, 10, 40)
    add_label: bool = True
    label_style: str = "wb"
    inset_fraction: any = (0.1,0.07)
    strain_diff_range: list[float] = field(default_factory=list)
    strain_rotation_range: list[float] = field(default_factory=list)
    mae_diff_range: list[float] = field(default_factory=list)
    mae_rotation_range: list[float] = field(default_factory=list)

    """ class for visualizing and comparing 

    Args:
        rotation (numpy.array): rotation value generated by neural network
        scale_shear (numpy.array): scale and shear value generated by neural network
        file_py4DSTEM (str): hdf5 file of affine parameter generated by py4DSTEM
        label_rotation_path (str):  directory of label rotation  
        label_xx_path (str): directory of label scale x  
        label_yy_path (str): directory of label scale y 
        label_xy_path (str): directory of label shear  
        noise_intensity (float): determine the background noise intensity of the simulated 4dstem
        folder_name (str): save the generated figure to folder
        cmap_strain (str): color map of plt.imshow
        cmap_rotation (str): color map of plt.imshow
        cmap_mae (str): color map of plt.imshow
        angle_shift (float): determine the additional degree add to the rotation for visualization
        im_size (tuple): size of the strain map
        ref_region (tuple): region in image to be considered as reference, (x_start, x_end, y_start, y_end).
        add_label (bool): determine if add label to the figure
        label_style (str, optional): determine if add label to figure. Defaults to 'wb'
        strain_diff_range (list): range of strain value for visualization
        strain_rotation_range (list): range of rotation value for visualization
        mae_diff_range (list): range of strain and shear difference in visualization
        mae_rotation_range (list): range of rotation difference in visualization

    """

    def __post_init__(self):
        # load various labels of affine parameter
        self.label_rotation, self.label_xx, self.label_yy, self.label_xy = (
            self.load_transformation()
        )

        # load the h5 file of py4DSTEM results
        f = h5py.File(self.file_py4DSTEM)
        self.strain_map = f["strain_map_root"]["strain_map"]["data"][:]

        # compare performance of rotation value and visualize it
        self.theta_correlation, self.theta_ae = self.compare_rotation(
            title_name=self.noise_intensity,
            cmap=self.cmap_rotation,
            add_label=self.add_label,
            label_style=self.label_style,
            inset_fraction=self.inset_fraction
        )

        # calculate mean value of py4DSTEM rotation in reference region
        self.theta_ref_correlation = np.mean(
            self.theta_correlation[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )
        # calculate corresponding rotation based on reference
        self.theta_correlation = self.theta_correlation - self.theta_ref_correlation
        # calculate mean value of neural network rotation in reference region
        self.theta_ref_ae = np.mean(
            self.theta_ae[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )
        # calculate corresponding rotation based on reference
        self.theta_ae = self.theta_ae - self.theta_ref_ae

        # generate affine matrices with affine parameters
        self.M_init = basis2probe(self.rotation, self.scale_shear).reshape(
            self.im_size[0], self.im_size[1], 2, 2
        )

        # set additional angle dictionary for rotation comparison
        self.add_angle_shift = {
            "00": 25,
            "05": -7,
            "10": -5,
            "15": -8,
            "20": -7,
            "25": -9,
            "30": -9,
            "35": -6,
            "40": -8,
            "45": -7,
            "50": -6,
            "60": -9,
            "70": -8,
        }
        # initial list of dictionary to future plots
        self.list_of_dic = [
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
            {},
        ]

    def load_transformation(self):
        label_rotation = self.correct_rotation()
        label_xx = np.load(self.label_xx_path)
        label_yy = np.load(self.label_yy_path)
        label_xy = np.load(self.label_xy_path)

        return label_rotation, label_xx, label_yy, label_xy

    def correct_rotation(self):
        label_rotation = np.load(self.label_rotation_path)
        label_rotation = np.rad2deg(label_rotation)

        # calculate mean value of label rotation in reference region
        label_ref_rotation = np.mean(
            label_rotation[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )

        # calculate corresponding rotation based on reference
        return label_rotation - label_ref_rotation

    def compare_rotation(
        self,
        title_name="WS2WSe2",
        cmap="RdBu_r",
        shift_ref=0,
        img_size=(256, 256),
        clim=[0, 60],
        inverse_rotation=False,
        save_figure=True,
        add_label=True,
        label_style="wb",
        inset_fraction = (0.1,0.07),
        **kwargs,
    ):
        """function to compare rotation map between results of neural network and py4DSTEM

        Args:
            strain_map (numpy.array): strain map results generated by py4DSTEM
            rotation_ (numpy.array): rotation matrix generated by neural network
            classification (numpy.array, optional): If exists, classification map generated by neural network. Defaults to None.
            bkg_index (numpy.array, optional): if classification is not None, index of background map. Defaults to None.
            sample_index (numpy.array, optional): if classification is not None, index of sample map. Defaults to None.
            title_name (str, optional): name of the figure. Defaults to 'WS2WSe2'.
            cmap (str): color map of plt.imshow.
            angle_shift (float, optional): angle degree shift on rotation map neural network. Defaults to 0.
            shift_ref (float, optional): angle degree shift on rotation map py4DSTEM. Defaults to 0.
            img_size (tuple, optional): size of the rotation map. Defaults to (256,256).
            clim (list, optional): visualization range of rotation value. Defaults to [0,60].
            save_figure (bool, optional): determine save or not.
            add_label (bool, optional): determine if add label to the figure.
            label_style (str, optional): determine if add label to figure. Defaults to 'wb'.

        Returns:
            numpy.array: adjusted of rotation value for py4DSTEM and neural network
        """
        kwargs.setdefault("inset_fraction", inset_fraction)
        kwargs.setdefault("style", label_style)
        ref_clim = kwargs.get("ref_clim", clim)
        background_index = kwargs.get("background_index", None)
        sample_index = kwargs.get("sample_index", None)
        rotational_symmetry_degree = kwargs.get("rotational_symmetry_degree", 60)

        # set name of the figure
        name_ = self.get_title(title_name)

        # switch format to degree for each rotation value, mod by 60 to make it distributed in (0, 60)
        theta_correlation = self.extract_shifted_rotation_degrees(
            shift_ref, rotational_symmetry_degree
        )
        # theta_correlation[background_index] = 0

        temp_ae = self.inverse_rotational_transformation(
            self.angle_shift, inverse_rotation, rotational_symmetry_degree
        )
        theta_ae = self.zero_background(
            background_index, sample_index, img_size, temp_ae
        )

        # reshape the rotation map into 2D image size
        theta_correlation = theta_correlation.reshape(img_size)
        theta_ae = theta_ae.reshape(img_size)

        # visualize the rotation map and histogram
        fig, ax = subfigures(2, 2, gaps=(0.4, 0.1))
        ax = np.array(ax).reshape(2, 2)

        remove_all_ticks([ax[0, 0], ax[0, 1]])

        im1 = ax[0, 0].imshow(
            theta_correlation,
            cmap=cmap,
            vmin=ref_clim[0],
            vmax=ref_clim[1],
        )
        add_colorbar(im1, ax[0, 0])

        ax[1, 0].hist(theta_correlation.reshape(-1), 200, range=ref_clim)
        im2 = ax[0, 1].imshow(
            theta_ae,
            cmap=cmap,
            vmin=clim[0],
            vmax=clim[1],
        )
        add_colorbar(im2, ax[0, 1])

        ax[1, 1].hist(theta_ae.reshape(-1), 200, range=clim)

        ax[1, 0].xaxis.set_label_text("Rotation (degree)")
        ax[1, 1].xaxis.set_label_text("Rotation (degree)")
        if add_label:
            labelfigs(
                ax[0, 0], string_add="Py4DSTEM", loc="ct", inset_fraction=(inset_fraction[0],0), style= label_style
            )
            labelfigs(
                ax[0, 1], string_add="Auto4DSTEM", loc="ct", inset_fraction=(inset_fraction[0],0), style= label_style
            )
        if save_figure:
            print(self.folder_name)
            filtered_kwargs = filter_kwargs(Printer, kwargs)
            printer = Printer(basepath=self.folder_name, **filtered_kwargs)
            printer.savefig(
                fig, f"/Rotation_comparison_on_{name_}", label_figs=ax.ravel(), **kwargs
            )

        return theta_correlation, theta_ae

    def zero_background(self, background_index, sample_index, img_size, temp_ae):
        if background_index is not None:
            # make rotation map region where belongs to background become 0, keep sample region value.
            theta_ae = np.zeros([img_size[0] * img_size[1]])
            theta_ae[sample_index] = temp_ae
            return theta_ae
        else:
            return temp_ae

    def inverse_rotational_transformation(
        self, angle_shift, inverse_rotation, rotational_symmetry_degree
    ):
        rotation_ = rotational_symmetry_degree if inverse_rotation else 0
        inverse_rotation_ = -1 if inverse_rotation else 1

        temp_ae = np.mod(
            angle_shift
            + rotation_
            + inverse_rotation_
            * np.rad2deg(
                np.arctan2(
                    self.rotation[:, 1].reshape(-1), self.rotation[:, 0].reshape(-1)
                )
            ),
            rotational_symmetry_degree,
        )

        return temp_ae

    def extract_shifted_rotation_degrees(self, shift_ref, rotational_symmetry_degree):
        return np.mod(
            shift_ref + np.rad2deg(self.strain_map[3, :, :]), rotational_symmetry_degree
        ).reshape(-1)

    @staticmethod
    def get_title(title_name):
        if isinstance(title_name, str):
            name_ = title_name
        else:
            name_ = format(title_name, ".2f") + " Background Noise"
        return name_

    def reset_baseline(self):
        """
        function to reload the h5 file of py4DSTEM results
        """

        f = h5py.File(self.file_py4DSTEM)
        self.strain_map = f["strain_map_root"]["strain_map"]["data"][:]

    def add_dictionary(self, **kwargs):
        """function to add key value pairs to dictionary"""
        self.add_angle_shift.update(kwargs)

    def reset_angle(self, angle_shift, label_style=None):
        """function to compare performance of rotation value and visualize it

        Args:
            angle_shift (float): additional degree value added to the rotation of neural network
            label_style (str, optional): determine label style. Defaults to None
        """
        # initial label style
        if label_style is not None:
            self.label_style = label_style
        self.angle_shift = angle_shift
        # compare performance of rotation value and visualize it
        self.theta_correlation, self.theta_ae = self.compare_rotation(
            title_name=self.noise_intensity,
            cmap=self.cmap_rotation,
            angle_shift=self.angle_shift,
            add_label=self.add_label,
            label_style=self.label_style,
            inset_fraction=self.inset_fraction
        )
        # calculate mean value of py4DSTEM rotation in reference region
        self.theta_ref_correlation = np.mean(
            self.theta_correlation[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )
        # calculate corresponding rotation based on reference
        self.theta_correlation = self.theta_correlation - self.theta_ref_correlation
        # calculate mean value of neural network rotation in reference region
        self.theta_ref_ae = np.mean(
            self.theta_ae[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )
        # calculate corresponding rotation based on reference
        self.theta_ae = self.theta_ae - self.theta_ref_ae

    def reset_polar_matrix(self):
        """
        function to reload affine matrices with affine parameters
        """

        self.M_init = basis2probe(self.rotation, self.scale_shear).reshape(
            self.im_size[0], self.im_size[1], 2, 2
        )

    def visual_strain(self, 
                    label_style=None,
                    inset_fraction = None):
        """
        function to visualize strain comparison between results of py4DSTEM and neural network
        label_style (str, optional): determine label style. Defaults to None
        inset_fraction (tuple, optional): determine inset fraction. Defaults to None
        """
        # initial label style:
        if label_style is not None:
            self.label_style = label_style
        if inset_fraction is not None:
            self.inset_fraction = inset_fraction
        # get strain parameters of neural network from strain_tensor function
        self.exx_ae, self.eyy_ae, self.exy_ae = strain_tensor(
            self.M_init, self.im_size, self.ref_region
        )
        # load strain parameters of py4DSTEM from strain map file
        self.exx_correlation = self.strain_map[0, :, :]
        self.eyy_correlation = self.strain_map[1, :, :]
        self.exy_correlation = self.strain_map[2, :, :]
        # create strain list to be the input of the Strain_Compare function
        self.strain_list = [
            self.exx_correlation,
            self.eyy_correlation,
            self.exy_correlation,
            self.theta_correlation,
            self.exx_ae,
            self.eyy_ae,
            self.exy_ae,
            self.theta_ae,
        ]
        # save results in h5
        hf = h5py.File(
            f"{self.folder_name}/{self.noise_intensity}_simulated_strain_list.h5", "w"
        )
        hf.create_dataset(f"py4d", data=self.strain_list[0:4])
        hf.create_dataset(f"auto4d", data=self.strain_list[4:])
        hf.close()
        # visualize strain comparison between results of py4DSTEM and neural network
        Strain_Compare(
            self.strain_list,
            ae_xx_diff_range=self.strain_diff_range,
            ae_yy_diff_range=self.strain_diff_range,
            ae_xy_diff_range=self.strain_diff_range,
            cross_xx_diff_range=self.strain_diff_range,
            cross_yy_diff_range=self.strain_diff_range,
            cross_xy_diff_range=self.strain_diff_range,
            rotation_range=self.strain_rotation_range,
            title_name=self.noise_intensity,
            folder_name=self.folder_name,
            cmap_strain=self.cmap_strain,
            cmap_rotation=self.cmap_rotation,
            add_label=self.add_label,
            label_style=self.label_style,
            inset_fraction= self.inset_fraction,
        )

    def visual_diff(self, label_style=None,inset_fraction=None):
        """
        function to visualize difference between label and model generated results
        label_style (str, optional): determine the type of label style. Defaults to None
        """
        if label_style is not None:
            self.label_style = label_style
        if inset_fraction is not None:
            self.inset_fraction = inset_fraction
        #  calculate difference between label and model generated results
        self.list_of_difference = cal_diff(
            self.exx_correlation,
            self.eyy_correlation,
            self.exy_correlation,
            self.theta_correlation,
            self.exx_ae,
            self.eyy_ae,
            self.exy_ae,
            self.theta_ae,
            self.label_xx,
            self.label_yy,
            self.label_xy,
            self.label_rotation,
        )

        # visualize difference between label and model generated results
        MAE_diff_with_Label(
            diff_list=self.list_of_difference,
            diff_range=self.mae_diff_range,
            rotation_range=self.mae_rotation_range,
            noise_intensity=self.noise_intensity,
            folder_name=self.folder_name,
            cmap=self.cmap_mae,
            data_index=None,
            add_title=self.add_label,
            label_style=self.label_style,
            inset_fraction = self.inset_fraction
        )

    def record_performance(
        self,
        ste_dic=False,
        data_index_path="",
        data_index=False,
        width=2,
        show_index_map=False,
    ):
        """function to extract standard deviation of both py4dstem and auto4dstem

        Args:
            ste_dic (bool, optional): determine if save standard error. Defaults to False.
            data_index_path (str, optional): path of the data index. Defaults to ''.
            data_index (bool, optional): determine if calculate std only on sample region. Defaults to False.
            width (int, optional): scale of boundary size. Defaults to 2.
            show_index_map (bool, optional): determine if need to show the sample image. Defaults to False.
        """
        # calculate the size of sample
        num_index = int(self.im_size[0] * self.im_size[1])
        # calculate the number of sample and create sample index according to insert sample index
        if data_index:
            # load data
            load_index = np.load(data_index_path).reshape(-1)
            img = np.zeros([self.im_size[0] * self.im_size[1]])
            img[load_index] = 1
            # calculate sample index
            sq = morphology.square(width=width)
            img = binary_erosion(img.reshape(self.im_size), sq)
            # show sample index map
            if show_index_map:
                plt.imshow(img)
                plt.setp(plt.gcf().get_axes(), xticks=[], yticks=[])
            self.sample_index_4_std = img.reshape(-1)
            # calculate the size of sample
            num_index = int(np.sum(self.sample_index_4_std))
        # initial key name for dictionary
        self.key_name = [
            "exx_correlation",
            "eyy_correlation",
            "exy_correlation",
            "theta_correlation",
            "exx_ae",
            "eyy_ae",
            "exy_ae",
            "theta_ae",
        ]
        # initial dictionary
        self.mae_dictionary = {}
        self.std_dictionary = {}
        # initial ste if set to True
        if ste_dic:
            self.ste_dictionary = {}
        # update dictionary by key value pair
        for i in range(len(self.list_of_difference)):
            # calculate mae, std and ste
            mae_ = np.mean(abs(self.list_of_difference[i].reshape(-1)))
            if data_index:
                std_ = np.std(
                    (self.list_of_difference[i].reshape(-1))[self.sample_index_4_std]
                )
            else:
                std_ = np.std(self.list_of_difference[i].reshape(-1))
            # update key value pair into dictionary
            self.mae_dictionary.update({self.key_name[i]: mae_})
            self.std_dictionary.update({self.key_name[i]: std_})
            if ste_dic:
                ste_ = std_ / np.sqrt(num_index)
                self.ste_dictionary.update({self.key_name[i]: ste_})

    def add_data_2_plot(self, ste_dic=False):
        """function to insert values into different dictionaries

        Args:
            ste_dic (bool, optional): determine use std dictionary or ste dictionary. Defaults to False.
        """
        # generate key value
        bkg_str = format(int(self.noise_intensity * 100), "02d")
        # determine target dictionary
        dic1 = self.mae_dictionary
        if ste_dic:
            dic2 = self.ste_dictionary
        else:
            dic2 = self.std_dictionary
        # extract key value pairs
        ict_1 = list(dic1.items())
        ict_2 = list(dic2.items())
        # insert value to each dictionary
        for i in range(8):
            self.list_of_dic[i].update({bkg_str: ict_1[i][1]})
        for j in range(8, 16):
            self.list_of_dic[j].update({bkg_str: ict_2[j - 8][1]})

    def extract_ele_from_dic(self, num):
        """function to generate x,y pairs to plot

        Args:
            num (int): index of the list of dictionary

        Returns:
            np.array, np.array: x, y pair
        """
        x_ = []
        y_ = []
        x_list = sorted(self.list_of_dic[num].keys())
        for i in x_list:
            y_.append(self.list_of_dic[num][i])
            x_.append(int(i) / 100)
        x_ = np.array(x_)
        y_ = np.array(y_)

        return x_, y_

    def visual_label_map(
        self,
        save_figure=True,
        cmap_strain="viridis",
        cmap_rotation="viridis",
        add_label=True,
        label_style="wb",
        inset_fraction = (0.1, 0.05),
        **kwargs,
    ):
        """function to visualize strain map of label

        Args:
            shrink (float, optional): control the size of colorbar. Defaults to 0.7.
            save_figure (bool, optional): determine if saving figure needed. Defaults to True.
            cmap (str): color map of plt.imshow. Default to 'viridis'.
            add_label (bool, optional): determine if add label to figure. Default to True.
            label_style (str, optional): determine label style. Defaults to 'wb'
        """
        fig, ax = subfigures(2, 2, gaps=(0.4, 0.1))
        kwargs.setdefault("inset_fraction", inset_fraction)
        kwargs.setdefault("style", label_style)
        ax = np.array(ax).reshape(2, 2)
        # create list of data and corresponding color range
        label_list = [self.label_xx, self.label_xy, self.label_yy, self.label_rotation]
        clim_list = [
            self.strain_diff_range,
            self.strain_diff_range,
            self.strain_diff_range,
            self.strain_rotation_range,
        ]
        # determine the row and colum value
        for i in range(4):
            # generate color map
            if i == 3:
                cmap = cmap_rotation
            else:
                cmap = cmap_strain
            # generate row and colum
            if int(i / 2) == 0:
                row = i
                col = 0
            else:
                row = i - 2
                col = 1
            # plot image show strain map and color bar.
            im = ax[row, col].imshow(label_list[i], cmap=cmap, clim=clim_list[i])
            add_colorbar(im, ax[row, col])
 
        # set title of each label
        labelfigs(
            ax[0, 0], string_add="Strain X", loc="ct", inset_fraction=(inset_fraction[0],0), style = label_style
        )
        labelfigs(
            ax[0, 1], string_add="Strain Y", loc="ct", inset_fraction=(inset_fraction[0],0), style = label_style
        )
        labelfigs(
            ax[1, 0], string_add="Shear", loc="ct", inset_fraction=(inset_fraction[0],0), style = label_style
        )
        labelfigs(
            ax[1, 1], string_add="Rotation", loc="ct",  inset_fraction=(inset_fraction[0],0), style = label_style
        )
        remove_all_ticks(ax[0,0],ax[0,1],ax[1,0],ax[1,1])
        # save figure
        if save_figure:
            filtered_kwargs = filter_kwargs(Printer, kwargs)
            printer = Printer(basepath=self.folder_name, **filtered_kwargs)
            printer.savefig(
                fig, f"/Strain_Map_of_Label", label_figs=ax.ravel(), **kwargs
            )

    def show_normalized_comparison_results(
        self,
        noise_intensity=[0, 0.15, 0.70],
        color_list=["red", "green", "blue", "orange", "grey", "purple"],
        save_figure=True,
    ):
        """function to show normalized comparison of py4dstem and auto4dstem

        Args:
            noise_intensity (list, optional): _description_. Defaults to [0,0.15,0.70].
            color_list (list, optional): _description_. Defaults to ['red','green','blue','orange','grey','purple'].
            save_figure (bool, optional): determine save or not.
        """
        # set color represents each noise intensity
        if len(color_list) < len(noise_intensity):
            return "not enough color to represent noise level"
        # initial file pre
        file_name = "Noise_Intensity_"
        # sort noise intensity list
        noise_intensity.sort(reverse=True)
        # generate figure
        fig, ax = plt.subplots(4, 3, figsize=(15, 20))
        # add title to each subplot
        ax[0, 0].title.set_text("Strain X:  Label")
        ax[0, 1].title.set_text("Py4DSTEM")
        ax[0, 2].title.set_text("Auto4DSTEM")
        ax[1, 0].title.set_text("Strain Y:  Label")
        ax[1, 1].title.set_text("Py4DSTEM")
        ax[1, 2].title.set_text("Auto4DSTEM")
        ax[2, 0].title.set_text("Shear:  Label")
        ax[2, 1].title.set_text("Py4DSTEM")
        ax[2, 2].title.set_text("Auto4DSTEM")
        ax[3, 0].title.set_text("Rotation:  Label")
        ax[3, 1].title.set_text("Py4DSTEM")
        ax[3, 2].title.set_text("Auto4DSTEM")

        #  generate label histograms
        hist_plotter(ax[0, 0], self.label_xx, "blue", clim=self.strain_diff_range)
        hist_plotter(ax[1, 0], self.label_yy, "blue", clim=self.strain_diff_range)
        hist_plotter(ax[2, 0], self.label_xy, "blue", clim=self.strain_diff_range)
        hist_plotter(
            ax[3, 0], self.label_rotation, "blue", clim=self.strain_rotation_range
        )

        for i, bkg_intensity in enumerate(noise_intensity):
            # complete file name
            bkg_str = format(int(bkg_intensity * 100), "02d")
            file_name += f"{bkg_str}_"
            # load py4dstem results
            py4dstem_path = (
                f"{self.folder_name}/analysis_bg{bkg_str}per_1e5counts__strain.h5"
            )
            f = h5py.File(py4dstem_path)
            strain_map = f["strain_map_root"]["strain_map"]["data"][:]
            # extract strain value
            exx_correlation = strain_map[0, :, :]
            eyy_correlation = strain_map[1, :, :]
            exy_correlation = strain_map[2, :, :]
            # load auto4dstem results
            rotation_path = (
                f"{self.folder_name}/{bkg_str}Per_2_train_process_rotation.npy"
            )
            strain_path = (
                f"{self.folder_name}/{bkg_str}Per_2_train_process_scale_shear.npy"
            )
            rotation_ = np.load(rotation_path)
            scale_shear_ = np.load(strain_path)
            # determine the value of additional angle added to angle shift
            if bkg_str not in self.add_angle_shift:
                angle_shift = 0
            else:
                angle_shift = self.add_angle_shift[bkg_str]
            # compare performance of rotation value and visualize it
            theta_correlation = np.mod(np.rad2deg(strain_map[3, :, :]), 60).reshape(
                self.im_size
            )

            theta_ae = np.mod(
                angle_shift
                + 1
                * np.rad2deg(
                    np.arctan2(rotation_[:, 1].reshape(-1), rotation_[:, 0].reshape(-1))
                ),
                60.0,
            ).reshape(self.im_size)
            # calculate mean value of py4DSTEM rotation in reference region
            theta_ref_correlation = np.mean(
                theta_correlation[
                    self.ref_region[0] : self.ref_region[1],
                    self.ref_region[2] : self.ref_region[3],
                ]
            )
            # calculate mean value of neural network rotation in reference region
            theta_ref_ae = np.mean(
                theta_ae[
                    self.ref_region[0] : self.ref_region[1],
                    self.ref_region[2] : self.ref_region[3],
                ]
            )
            # calculate corresponding rotation based on reference
            theta_correlation = theta_correlation - theta_ref_correlation
            # calculate corresponding rotation based on reference
            theta_ae = theta_ae - theta_ref_ae
            # generate strain value
            M_init = basis2probe(rotation_, scale_shear_).reshape(
                self.im_size[0], self.im_size[1], 2, 2
            )
            exx_ae, eyy_ae, exy_ae = strain_tensor(M_init, self.im_size)
            # generate py4dstem and auto4dstem histograms
            hist_plotter(
                ax[0, 1],
                exx_correlation,
                color=color_list[i],
                clim=self.strain_diff_range,
            )
            hist_plotter(
                ax[0, 2], exx_ae, color=color_list[i], clim=self.strain_diff_range
            )
            hist_plotter(
                ax[1, 1],
                eyy_correlation,
                color=color_list[i],
                clim=self.strain_diff_range,
            )
            hist_plotter(
                ax[1, 2], eyy_ae, color=color_list[i], clim=self.strain_diff_range
            )
            hist_plotter(
                ax[2, 1],
                exy_correlation,
                color=color_list[i],
                clim=self.strain_diff_range,
            )
            hist_plotter(
                ax[2, 2], exy_ae, color=color_list[i], clim=self.strain_diff_range
            )
            hist_plotter(
                ax[3, 1],
                theta_correlation,
                color=color_list[i],
                clim=self.strain_rotation_range,
            )
            hist_plotter(
                ax[3, 2], theta_ae, color=color_list[i], clim=self.strain_rotation_range
            )
        fig.tight_layout()
        # save figure
        if save_figure:
            plt.savefig(f"{self.folder_name}/{file_name}compare_performance.svg")

    def show_normalized_results(
        self,
        strain=None,
        rotation=None,
        color="blue",
        file_name="",
        angle_shift=0,
        save_figure=True,
    ):
        """function to show normalized results

        Args:
            color_list (list, optional): _description_. Defaults to ['red','green','blue','orange','grey','purple'].
            im_size (tuple, optional): _description_. Defaults to (256,256).
            clim (list, optional): _description_. Defaults to [-0.03,0.03].
            file_name (str, optional): set file name of saved figure. Defaults to ''.
            save_figure (bool, optional): determine save or not.
        """
        # set color represents each noise intensity
        if strain is None:
            strain = self.scale_shear
        if rotation is None:
            rotation = self.rotation
        # generate figure
        fig, ax = plt.subplots(1, 4, figsize=(20, 5))
        # add title to each subplot
        ax[0].title.set_text("Strain X")
        ax[1].title.set_text("Strain Y")
        ax[2].title.set_text("Shear")
        ax[3].title.set_text("Rotation")

        theta_ae = np.mod(
            angle_shift
            + 1
            * np.rad2deg(
                np.arctan2(rotation[:, 1].reshape(-1), rotation[:, 0].reshape(-1))
            ),
            60.0,
        ).reshape(self.im_size)

        # calculate mean value of neural network rotation in reference region
        theta_ref_ae = np.mean(
            theta_ae[
                self.ref_region[0] : self.ref_region[1],
                self.ref_region[2] : self.ref_region[3],
            ]
        )
        # calculate corresponding rotation based on reference
        theta_ae = theta_ae - theta_ref_ae
        # generate strain value
        M_init = basis2probe(rotation, strain).reshape(
            self.im_size[0], self.im_size[1], 2, 2
        )
        exx_ae, eyy_ae, exy_ae = strain_tensor(M_init, self.im_size)
        # generate py4dstem and auto4dstem histograms
        hist_plotter(ax[0], exx_ae, color=color, clim=self.strain_diff_range)
        hist_plotter(ax[1], eyy_ae, color=color, clim=self.strain_diff_range)
        hist_plotter(ax[2], exy_ae, color=color, clim=self.strain_diff_range)
        hist_plotter(ax[3], theta_ae, color=color, clim=self.strain_rotation_range)
        fig.tight_layout()
        # save figure
        if save_figure:
            plt.savefig(f"{self.folder_name}/{file_name}_normalized_strain_results.svg")

        return exx_ae, eyy_ae, exy_ae, theta_ae
